version: "3.7"

services:
  nextjs:
    image: "web"
    user: root
    # for logger file
    privileged: true
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: ./apps/nextjs/Dockerfile
    environment:
      - DEBUG=true
